### PR TITLE
try/except block to catch AttributeErrors in OAI records w/ no metadata child

### PR DESCRIPTION
**Pull request by mrmiguez**
Fix for issue #37

### CODE REVIEW

**Comment by mloesch** [comment]
According to the OAI-PMH specification the `metadata` XML element is not optional:
http://www.openarchives.org/OAI/openarchivesprotocol.html#Record

I suggest that you register your own record implementation as described here:
https://sickle.readthedocs.io/en/latest/customizing.html

I suppose we could make this a bit easier by extracting the population of the metadata property to a method `Record.get_metadata()`

**Comment by mrmiguez** [comment]
I agree. Moving the population of `self.metadata` out of `__init__` to a separate method will make sub-classing easier.

My current dirty hack to make this work in my repo is to sub-class `sickle.models.Record` but make the `super` call to `OAIItem`.

**Comment by mloesch** [comment]
👍 manually merged

**Comment by mloesch** [comment]
fixed in release 0.7.0

**Pull request closed without merging**
